#! /usr/bin/env bash

set -euo pipefail

browse() {
    open "$(project_url "/tree/%s" "$(current_branch)")"
}

current_branch() {
    git symbolic-ref --quiet --short HEAD
}

merge_requests() {
    open "$(project_url "/merge_requests")"
}

pipelines() {
    open "$(project_url "/pipelines")"
}

project_url() {
    local format=$1
    shift
    printf "%s$format" \
        "$(git remote get-url origin \
            | sed -e 's|:|/|' \
                -e 's|^git@|https://|' \
                -e 's/\.git$//')" \
        "$@"
}

usage() {
    echo "TOOD: write usage"
    exit "$1"
}

case $1 in
    browse | brwose)
        browse
        ;;
    mr | mrs)
        merge_requests
        ;;
    pipe | pipes | pipeline | pipelines)
        pipelines
        ;;
    *)
        usage 100
        ;;
esac
