#! /usr/bin/env bash
set -eufo pipefail

case "$OSTYPE" in
    linux*)
        _open="xdg-open"
        ;;
    darwin*)
        _open="open"
        ;;
esac

browse() {
    "$_open" "$(project_url "/tree/%s" "$(current_branch)")"
}

current_branch() {
    git symbolic-ref --quiet --short HEAD
}

merge_requests() {
    "$_open" "$(project_url "/merge_requests")"
}

pipelines() {
    "$_open" "$(project_url "/pipelines")"
}

repo_url() {
    git remote get-url origin \
        | sed -E \
            -e 's,^git@([^:]+):,https://\1/,' \
            -e 's,\.git$,,'
}

project_url() {
    local format="$1"
    shift
    printf "%s$format" "$(repo_url)" "$@"
}

usage() {
    echo "${0} [br{ow,wo}se | mr{,s} | pip{s,line,lines}]"
    exit "$1"
}

case "${1:-}" in
    browse | brwose)
        browse
        ;;
    mr | mrs)
        merge_requests
        ;;
    pipe | pipes | pipeline | pipelines)
        pipelines
        ;;
    *)
        usage 100
        ;;
esac
